default_region: "USA"
default_language: "En"

datetime_format: "%Y/%m/%d, %H:%M:%S"

platforms:
  - "Nintendo - GameCube"
  - "Nintendo - Nintendo Entertainment System"
  - "Nintendo - Super Nintendo Entertainment System"
  - "Sony - PlayStation"
  - "Sony - PlayStation 2"

video_types:
  - "NTSC"
  - "PAL"
  - "PAL 60Hz"
  - "MPAL"
  - "SECAM"

regions:
  USA: "USA"
  World: "World"
  Canada: "Canada"
  Europe: "Europe"
  UK: "UK|United Kingdom"
  Australia: "Australia"
  New Zealand: "New Zealand"
  Singapore: "Singapore"
  Ireland: "Ireland"
  Japan: "Japan"
  Asia: "Asia"
  Thailand: "Thailand"
  Spain: "Spain"
  Mexico: "Mexico"
  Argentina: "Argentina"
  Latin America: "Latin America"
  Brazil: "Brazil"
  Portugal: "Portugal"
  France: "France"
  Belgium: "Belgium"
  Netherlands: "Netherlands"
  Germany: "Germany"
  Austria: "Austria"
  Italy: "Italy"
  Switzerland: "Switzerland"
  Hong Kong: "Hong Kong"
  China: "China"
  Taiwan: "Taiwan"
  Korea: "Korea"
  Russia: "Russia"
  Ukraine: "Ukraine"
  Estonia: "Estonia"
  Poland: "Poland"
  Latvia: "Latvia"
  Lithuania: "Lithuania"
  Denmark: "Denmark"
  Norway: "Norway"
  Sweden: "Sweden"
  Scandinavia: "Scandinavia"
  Finland: "Finland"
  Iceland: "Iceland"
  Hungary: "Hungary"
  Czech: "Czech"
  Greece: "Greece"
  Macedonia: "Macedonia"
  India: "India"
  South Africa: "South Africa"
  Israel: "Israel"
  Slovakia: "Slovakia"
  Turkey: "Turkey"
  Croatia: "Croatia"
  Slovenia: "Slovenia"
  United Arab Emirates: "United Arab Emirates"
  Bulgaria: "Bulgaria"
  Romania: "Romania"
  Albania: "Albania"
  Serbia: "Serbia"
  Indonesia: "Indonesia"
  Unknown: "Unknown"

languages:
  English: "En(?:-[A-Z][A-Z])?"
  Afrikaans: "Af"
  Albanian: "Sq"
  Arabic: "Ar"
  Basque: "Eu"
  Bulgarian: "Bg"
  Catalan: "Ca"
  Chinese (Simplified): "Zh-Hans|Zh"
  Chinese (Traditional): "Zh-Hant|Zh"
  Cornish: "Kw"
  Croatian: "Hr"
  Czech: "Cs"
  Danish: "Da"
  Dutch: "Nl"
  Estonian: "Et"
  Finnish: "Fi"
  French: "Fr(?!-CA)(?:-[A-Z][A-Z])?"
  French (Canadian): "Fr-CA"
  Gaelic: "Gd"
  German: "De"
  Greek: "El"
  Hebrew: "He"
  Hindi: "Hi"
  Hungarian: "Hu"
  Icelandic: "Is"
  Indonesian: "Id"
  Italian: "It"
  Japanese: "Ja"
  Korean: "Ko"
  Latvian: "Lv"
  Lithuanian: "Lt"
  Macedonian: "Mk"
  Norwegian: "No"
  Polish: "Pl"
  Portuguese: "Pt(?!-BR)(?:-[A-Z][A-Z])?"
  Portuguese (Brazilian): "Pt-BR"
  Punjabi: "Pa"
  Romanian: "Ro"
  Russian: "Ru"
  Serbian: "Sr"
  Slovak: "Sk"
  Slovenian: "Sl"
  Spanish: "Es(?!-(MX|XL))(?:-[A-Z][A-Z])?"
  Spanish (Latin American): "Es-XL"
  Spanish (Mexican): "Es-MX"
  Swedish: "Sv"
  Tamil: "Ta"
  Thai: "Th"
  Turkish: "Tr"
  Ukranian: "Uk"

dat_categories:
  - "Add-Ons"
  - "Applications"
  - "Audio"
  - "Console"
  - "Bonus Discs"
  - "Coverdiscs"
  - "Demos"
  - "Educational"
  - "Games"
  - "Manual"
  - "Multimedia"
  - "Preproduction"
  - "Promotional"
  - "Video"
