default_region: "USA"
default_language: "En"

datetime_format: "%Y/%m/%d, %H:%M:%S"

platforms:
  - "Nintendo - Game Boy"
  - "Nintendo - Game Boy Color"
  - "Nintendo - Game Boy Advance"
  - "Nintendo - Pokemon Mini"
  - "Nintendo - Nintendo Entertainment System"
  - "Nintendo - Super Nintendo Entertainment System"
  - "Nintendo - Nintendo 64"
  - "Nintendo - GameCube"
  - "Sega - Mega Drive - Genesis"
  - "Sony - PlayStation"
  - "Sony - PlayStation 2"
  - "Sony - PlayStation Portable"

video_types:
  - "NTSC"
  - "PAL"
  - "PAL 60Hz"
  - "MPAL"
  - "SECAM"

regions:
  USA: "USA"
  World: "World"
  Canada: "Canada"
  Europe: "Europe"
  UK: "UK|United Kingdom"
  Australia: "Australia"
  New Zealand: "New Zealand"
  Singapore: "Singapore"
  Ireland: "Ireland"
  Japan: "Japan"
  Asia: "Asia"
  Thailand: "Thailand"
  Spain: "Spain"
  Mexico: "Mexico"
  Argentina: "Argentina"
  Latin America: "Latin America"
  Brazil: "Brazil"
  Portugal: "Portugal"
  France: "France"
  Belgium: "Belgium"
  Netherlands: "Netherlands"
  Germany: "Germany"
  Austria: "Austria"
  Italy: "Italy"
  Switzerland: "Switzerland"
  Hong Kong: "Hong Kong"
  China: "China"
  Taiwan: "Taiwan"
  Korea: "Korea"
  Russia: "Russia"
  Ukraine: "Ukraine"
  Estonia: "Estonia"
  Poland: "Poland"
  Latvia: "Latvia"
  Lithuania: "Lithuania"
  Denmark: "Denmark"
  Norway: "Norway"
  Sweden: "Sweden"
  Scandinavia: "Scandinavia"
  Finland: "Finland"
  Iceland: "Iceland"
  Hungary: "Hungary"
  Czech: "Czech"
  Greece: "Greece"
  Macedonia: "Macedonia"
  India: "India"
  South Africa: "South Africa"
  Israel: "Israel"
  Slovakia: "Slovakia"
  Turkey: "Turkey"
  Croatia: "Croatia"
  Slovenia: "Slovenia"
  United Arab Emirates: "United Arab Emirates"
  Bulgaria: "Bulgaria"
  Romania: "Romania"
  Albania: "Albania"
  Serbia: "Serbia"
  Indonesia: "Indonesia"
  Unknown: "Unknown"

languages:
  English: "En(?:-[A-Z][A-Z])?"
  Afrikaans: "Af"
  Albanian: "Sq"
  Arabic: "Ar"
  Basque: "Eu"
  Bulgarian: "Bg"
  Catalan: "Ca"
  Chinese (Simplified): "Zh-Hans|Zh"
  Chinese (Traditional): "Zh-Hant|Zh"
  Cornish: "Kw"
  Croatian: "Hr"
  Czech: "Cs"
  Danish: "Da"
  Dutch: "Nl"
  Estonian: "Et"
  Finnish: "Fi"
  French: "Fr(?!-CA)(?:-[A-Z][A-Z])?"
  French (Canadian): "Fr-CA"
  Gaelic: "Gd"
  German: "De"
  Greek: "El"
  Hebrew: "He"
  Hindi: "Hi"
  Hungarian: "Hu"
  Icelandic: "Is"
  Indonesian: "Id"
  Italian: "It"
  Japanese: "Ja"
  Korean: "Ko"
  Latvian: "Lv"
  Lithuanian: "Lt"
  Macedonian: "Mk"
  Norwegian: "No"
  Polish: "Pl"
  Portuguese: "Pt(?!-BR)(?:-[A-Z][A-Z])?"
  Portuguese (Brazilian): "Pt-BR"
  Punjabi: "Pa"
  Romanian: "Ro"
  Russian: "Ru"
  Serbian: "Sr"
  Slovak: "Sk"
  Slovenian: "Sl"
  Spanish: "Es(?!-(MX|XL))(?:-[A-Z][A-Z])?"
  Spanish (Latin American): "Es-XL"
  Spanish (Mexican): "Es-MX"
  Swedish: "Sv"
  Tamil: "Ta"
  Thai: "Th"
  Turkish: "Tr"
  Ukranian: "Uk"

implied_languages:
  USA: "English"
  World: "English"
  Canada: "English"
  Europe: "English"
  UK: "English"
  Australia: "English"
  New Zealand: "English"
  Singapore: "English"
  Ireland: "English"
  Japan: "Japanese"
  Spain: "Spanish"
  Mexico: "Spanish (Mexican)"
  Argentina: "Spanish"
  Latin America: "Spanish (Latin American)"
  Brazil: "Portuguese (Brazilian)"
  Portugal: "Portuguese"
  France: "French"
  Belgium: "French"
  Netherlands: "Dutch"
  Germany: "German"
  Austria: "German"
  Italy: "Italian"
  Hong Kong: "Chinese (Traditional)"
  China: "Chinese (Simplified)"
  Taiwan: "Chinese (Traditional)"
  Korea: "Korean"
  Russia: "Russian"
  Estonia: "Estonian"
  Poland: "Polish"
  Latvia: "Latvian"
  Lithuania: "Lithuanian"
  Denmark: "Danish"
  Norway: "Norwegian"
  Sweden: "Swedish"
  Finland: "Finnish"
  Iceland: "Icelandic"
  Hungary: "Hungarian"
  Czech: "Czech"
  Greece: "Greek"
  Macedonia: "Macedonian"
  India: "English"
  Israel: "Hebrew"
  Slovakia: "Slovakian"
  Turkey: "Turkish"
  Croatia: "Croatian"
  Slovenia: "Slovenian"
  United Arab Emirates: "Arabic"
  Bulgaria: "Bulgarian"
  Romania: "Romanian"
  Albania: "Albanian"
  Serbia: "Serbian"
  Indonesia: "Indonesian"
  Unknown: "English"

dat_categories:
  - "Add-Ons"
  - "Applications"
  - "Audio"
  - "Console"
  - "Bonus Discs"
  - "Coverdiscs"
  - "Demos"
  - "Educational"
  - "Games"
  - "Manual"
  - "Multimedia"
  - "Preproduction"
  - "Promotional"
  - "Video"

dat_checksums:
  - "md5"
  - "sha1"
  - "sha256"

disc_rename:
  (Disc 0: "(Disc "
  (Disco : "(Disc "
  (Disk : "(Disc "
  (CD : "(Disc "
  (Disque : "(Disc "
  (Lato : "(Disc "
  (Seite : "(Disc "
  (Teil : "(Disc "
  (Disc ): "(Disc 0)"
  (Disc A): "(Disc 1)"
  (Disc B): "(Disc 2)"
  (Disc C): "(Disc 3)"
  (Disc D): "(Disc 4)"
  (Disc E): "(Disc 5)"
  (Disc F): "(Disc 6)"
  (Disc G): "(Disc 7)"
  (Disc H): "(Disc 8)"
  (Disc I): "(Disc 1)"
  (Disc II): "(Disc 2)"
  (Disc III): "(Disc 3)"
  (Disc IV): "(Disc 4)"
  (Disc V): "(Disc 5)"
  (Disc VI): "(Disc 6)"
  (Disc VII): "(Disc 7)"
  (Disc VIII): "(Disc 8)"
  (Disc One): "(Disc 1)"
  (Disc Two): "(Disc 2)"
  (Disc Three): "(Disc 3)"
  (Disc Four): "(Disc 4)"
  (Disc Five): "(Disc 5)"
  (Disc Six): "(Disc 6)"
  (Disc Seven): "(Disc 7)"
  (Disc Eight): "(Disc 8)"
  (Disc Uno): "(Disc 1)"
  (Disc Due): "(Disc 2)"
  (Disc Tre): "(Disc 3)"
  (Disc Quattro): "(Disc 4)"
  (Disc Cinque): "(Disc 5)"
  (Disc Sei): "(Disc 6)"
  (Disc Sette): "(Disc 7)"
  (Disc Otto): "(Disc 8)"
  (Disc-: "(Disc "
  (Disc Writer): "(Disk Writer)"

ra_file_exts:
  - ".bin"
  - ".bs"
  - ".iso"
  - ".fds"
  - ".gb"
  - ".gba"
  - ".gbc"
  - ".md"
  - ".ndd"
  - ".nds"
  - ".nes"
  - ".sfc"
  - ".sgb"
  - ".unf"
  - ".z64"
  - ".Z64"
  - ".zip"

ra_labels:
  - "redump"
  - "nointro"

ra_patch_checks:
  - "regions"
  - "version_no"
  - "revision"
  - "multi_disc"
  - "demos"
  - "preproduction"
  - "improved_version"
  - "modern_version"
  - "demoted_version"
