group: "Redump"
dir: "/Redump/Sony - PlayStation 2/"
unzip: true
file_exts:
  - ".iso"
  - ".bin"
  - ".cue"
compress: true
compress_method: "chdman"
compress_file_exts:
  - ".chd"

# RetroAchievements
ra_id: 21
ra_hash_method: "custom"

# ROMPatcher
patch_method: "xdelta"
patch_file_exts:
  - ".xdelta"
